version: "3.8"

services:
  opencart:
    container_name: opencart
    # build:
      # context: .
    image: als698/opencart:latest
    volumes:
      - ./web/oc:/var/www/html
      - ./web/storage:/var/www/storage
      - ./db:/db
    ports:
      - "80:8080"
    # environment:
      # IMPORT_DB: 1